OPERATION ASSIGN

The ASSIGN operation creates an output overlay in which every point is set to
the same, specified value.

The general form of the instruction for this operation is:

       AS[SIGN] number	 [F[OR] overlay]

where individual phrases are interpreted as follows.

       ASSIGN number   gives the value to be assigned.

       FOR overlay     gives the title of the output overlay. If omitted, the
		       title X is assumed.
