OPERATION PROTECT

The PROTECT operation sets the file protection indicator associated with an
input overlay to a protection status of "protected" such that that overlay is
protected from being modified. The EXPOSE operation has an opposite effect.

The general form of the instruction for this operation is:

       PROT[ECT] overlay

where:

       PROTECT overlay
		       gives the title of the overlay to be protected
