OPERATION COPY

The COPY operation creates an output overlay by reproducing the values,
labels, and scale of an input overlay.

The general form of the instruction for this operation is:

       COP[Y] overlay	[F[OR] overlay]

where individual phrases are interpreted as follows.

       COPY overlay    gives the title of the input overlay to be copied.

       FOR overlay     gives the title of the output overlay. If omitted, the
		       title X is assumed.
