OPERATION DESCRIBE

The DESCRIBE operation displays the legend of an input overlay.  Each overlay's
legend indicates its title, scale, and protection status, as well as the
values, labels (if any), and numbers of points associated with its regions.

The general form of the instruction for this operation is:

       DE[SCRIBE] overlay

where:

       DESCRIBE overlay
		       gives the title of the overlay to be described.
