OPERATION EXPLAIN

The EXPLAIN operation types out DOS text files of user information. A number of
these files are included as part of the Map Analysis Package. Additional files
can also be created in DOS with a text editing program. To be recognized by the
EXPLAIN operation, they must have DOS file names with the extension ".EX" and
be accessible from the current directory.

The general form of the instruction for this operation is:

       EXPL[AIN] name

where:

       EXPLAIN name    gives the name (without extension) of the DOS file to be
		       typed. If no name is specified, a list of all currently
		       available explanation files is produced.
