OPERATION EXPOSE

The EXPOSE operation sets the file protection indicator associated with an
input overlay to a protection status of "exposed" such that that overlay is no
longer protected from being modified.  The PROTECT operation has an opposite
effect.

The general form of the instruction for this operation is:

       EXPOS[E] overlay

where:

       EXPOSE overlay
		       gives the title of the overlay to be exposed.
